# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\"\"\n\x04\x64\x61ta\x12\x0b\n\x03\x61\x64r\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\"Z\n\x04html\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x19\n\x03res\x18\x02 \x01(\x0e\x32\x0c.html.Result\")\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\n\n\x06NOTADR\x10\x01\x12\x0b\n\x07NOTDATA\x10\x02\x32\x1d\n\x04\x44\x61ta\x12\x15\n\x03gen\x12\x05.data\x1a\x05.html\"\x00\x62\x06proto3')
)



_HTML_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='html.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTADR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTDATA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=99,
  serialized_end=140,
)
_sym_db.RegisterEnumDescriptor(_HTML_RESULT)


_DATA = _descriptor.Descriptor(
  name='data',
  full_name='data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adr', full_name='data.adr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='data.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=48,
)


_HTML = _descriptor.Descriptor(
  name='html',
  full_name='html',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='html.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res', full_name='html.res', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HTML_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=140,
)

_HTML.fields_by_name['res'].enum_type = _HTML_RESULT
_HTML_RESULT.containing_type = _HTML
DESCRIPTOR.message_types_by_name['data'] = _DATA
DESCRIPTOR.message_types_by_name['html'] = _HTML
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:data)
  })
_sym_db.RegisterMessage(data)

html = _reflection.GeneratedProtocolMessageType('html', (_message.Message,), {
  'DESCRIPTOR' : _HTML,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:html)
  })
_sym_db.RegisterMessage(html)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=142,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='gen',
    full_name='Data.gen',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_HTML,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
