# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class DataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.gen = channel.unary_unary(
        '/Data/gen',
        request_serializer=test__pb2.data.SerializeToString,
        response_deserializer=test__pb2.html.FromString,
        )


class DataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def gen(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'gen': grpc.unary_unary_rpc_method_handler(
          servicer.gen,
          request_deserializer=test__pb2.data.FromString,
          response_serializer=test__pb2.html.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Data', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
